#!/bin/bash -x

./add_matches_to_collection.py "02: Independent Content" "00 Rin"
./add_matches_to_collection.py "02: Independent Content" "Caelyx"
./add_matches_to_collection.py "02: Independent Content" "Clara Cosmia"
./add_matches_to_collection.py "02: Independent Content" "coffincouple"
./add_matches_to_collection.py "02: Independent Content" "Denver Maxx"
./add_matches_to_collection.py "02: Independent Content" "Effy Elizabeth"
./add_matches_to_collection.py "02: Independent Content" "Go Ask Alex"
./add_matches_to_collection.py "02: Independent Content" "Haelle"
./add_matches_to_collection.py "02: Independent Content" "Heather Carolin"
./add_matches_to_collection.py "02: Independent Content" "Heatherbby"
./add_matches_to_collection.py "02: Independent Content" "Invader Min"
./add_matches_to_collection.py "02: Independent Content" "Katopunk"
./add_matches_to_collection.py "02: Independent Content" "Kristie Bish"
./add_matches_to_collection.py "02: Independent Content" "Luna Lascivious"
./add_matches_to_collection.py "02: Independent Content" "Mayumouse"
./add_matches_to_collection.py "02: Independent Content" "Molly Stewart"
./add_matches_to_collection.py "02: Independent Content" "notfallenangel"
./add_matches_to_collection.py "02: Independent Content" "Puppy Girlfriend"
./add_matches_to_collection.py "02: Independent Content" "PuppyGirlfriend"
./add_matches_to_collection.py "02: Independent Content" "Rainbowslut"
./add_matches_to_collection.py "02: Independent Content" "RedAngeell"
./add_matches_to_collection.py "02: Independent Content" "Redhead Model Bundle"
./add_matches_to_collection.py "02: Independent Content" "RocknRose"
./add_matches_to_collection.py "02: Independent Content" "Shaiden"
./add_matches_to_collection.py "02: Independent Content" "SnugglePunk"
./add_matches_to_collection.py "02: Independent Content" "SpookyBooBoo"
./add_matches_to_collection.py "02: Independent Content" "Vivian Rose"
./add_matches_to_collection.py "02: Independent Content" "WildFresa"
