services:
  plexadm:
    image: ghcr.io/jasmeralia/plexscripts:sha-0a0a10d
    restart: "no"
    volumes:
      - /mnt/myzmirror/plexscripts/.plexconfig.ini:/root/.plexconfig.ini:ro
      - /mnt/myzmirror/plexscripts/reference:/app/reference:rw
    command: ["bash", "scripts/mass_process.sh"]
