#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/plexadm-env.sh"
"$PLEXADM" collection add-search "01: Category: Anal" "Anal"
"$PLEXADM" collection add-search "01: Category: Anal" "butt fuck"
"$PLEXADM" collection add-search "01: Category: Blackmail" "blackmail"
"$PLEXADM" collection add-search "01: Category: Blowjob" " BJ "
"$PLEXADM" collection add-search "01: Category: Blowjob" " Blow "
"$PLEXADM" collection add-search "01: Category: Blowjob" " oral "
"$PLEXADM" collection add-search "01: Category: Blowjob" "choked"
"$PLEXADM" collection add-search "01: Category: Blowjob" "face fuck"
"$PLEXADM" collection add-search "01: Category: Blowjob" "facefuck"
"$PLEXADM" collection add-search "01: Category: Blowjob" "gag"
"$PLEXADM" collection add-search "01: Category: Blowjob" "throat"
"$PLEXADM" collection add-search "01: Category: Butt Plug" " Plug "
"$PLEXADM" collection add-search "01: Category: Butt Plug" " buttplug "
"$PLEXADM" collection add-search "01: Category: Cheating" "cheating"
"$PLEXADM" collection add-search "01: Category: Deepthroat" "Face fuck"
"$PLEXADM" collection add-search "01: Category: Deepthroat" "throat"
"$PLEXADM" collection add-search "01: Category: Double Anal" "Double Anal"
"$PLEXADM" collection add-search "01: Category: Double Penetration" " DP "
"$PLEXADM" collection add-search "01: Category: Double Penetration" " Double Penetration "
"$PLEXADM" collection add-search "01: Category: Facial" "facial"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "daddy"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step brother"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step dad"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step daughter"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step mom"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step sis"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step-brother"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step-dad"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step-daughter"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step-mom"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "step-sis"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "stepbrother"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "stepdad"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "stepdaughter"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "stepmom"
"$PLEXADM" collection add-search "01: Category: Fauxcest" "stepsis"
"$PLEXADM" collection add-search "01: Category: Fingering" "finger"
"$PLEXADM" collection add-search "01: Category: Fuck Machine" "fuck machine"
"$PLEXADM" collection add-search "01: Category: Fuck Machine" "fuckmachine"
"$PLEXADM" collection add-search "01: Category: GFE" "gfe"
"$PLEXADM" collection add-search "01: Category: GFE" "girlfriend experience"
"$PLEXADM" collection add-search "01: Category: Goth" "goth"
"$PLEXADM" collection add-search "01: Category: Hot Wax" " wax "
"$PLEXADM" collection add-search "01: Category: Interview" " Interview"
"$PLEXADM" collection add-search "01: Category: Latex" "latex"
"$PLEXADM" collection add-search "01: Category: Lesbian" " gg "
"$PLEXADM" collection add-search "01: Category: Lesbian" "Lesbian"
"$PLEXADM" collection add-search "01: Category: Live Stream" "club show"
"$PLEXADM" collection add-search "01: Category: Live Stream" "cum show"
"$PLEXADM" collection add-search "01: Category: Live Stream" "cumshow"
"$PLEXADM" collection add-search "01: Category: Live Stream" "live stream"
"$PLEXADM" collection add-search "01: Category: Live Stream" "livestream"
"$PLEXADM" collection add-search "01: Category: Live Stream" "public show"
"$PLEXADM" collection add-search "01: Category: Orgy" " Orgies "
"$PLEXADM" collection add-search "01: Category: Orgy" "Orgy"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "Vibrator"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "bj tease"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "dildo"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "fuck machine"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "fuckmachine"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "hitachi"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "jessky"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "strap"
"$PLEXADM" collection add-search "01: Category: Sex Toys" "toy"
"$PLEXADM" collection add-search "01: Category: Solo" "herself"
"$PLEXADM" collection add-search "01: Category: Solo" "myself"
"$PLEXADM" collection add-search "01: Category: Strap On" "strap"
"$PLEXADM" collection add-search "01: Category: Teacher/Tutor" "Teacher"
"$PLEXADM" collection add-search "01: Category: Water" "shower"
"$PLEXADM" collection add-search "01: Hair: Blonde" "blond"
"$PLEXADM" collection add-search "01: Hair: Brunette" "brunette"
"$PLEXADM" collection add-search "01: Hair: Red" "Red head"
"$PLEXADM" collection add-search "01: Hair: Red" "Redhead"
