#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/plexadm-env.sh"
"$PLEXADM" collection add-search "01: Activity: Anal" "Anal"
"$PLEXADM" collection add-search "01: Activity: Anal" "butt fuck"
"$PLEXADM" collection add-search "01: Theme: Blackmail" "blackmail"
"$PLEXADM" collection add-search "01: Activity: Blowjob" " BJ "
"$PLEXADM" collection add-search "01: Activity: Blowjob" " Blow "
"$PLEXADM" collection add-search "01: Activity: Blowjob" " oral "
"$PLEXADM" collection add-search "01: Activity: Blowjob" "choked"
"$PLEXADM" collection add-search "01: Activity: Blowjob" "face fuck"
"$PLEXADM" collection add-search "01: Activity: Blowjob" "facefuck"
"$PLEXADM" collection add-search "01: Activity: Blowjob" "gag"
"$PLEXADM" collection add-search "01: Activity: Blowjob" "throat"
"$PLEXADM" collection add-search "01: Prop: Butt Plug" " Plug "
"$PLEXADM" collection add-search "01: Prop: Butt Plug" " buttplug "
"$PLEXADM" collection add-search "01: Theme: Cheating" "cheating"
"$PLEXADM" collection add-search "01: Activity: Deepthroat" "Face fuck"
"$PLEXADM" collection add-search "01: Activity: Deepthroat" "throat"
"$PLEXADM" collection add-search "01: Activity: Double Anal" "Double Anal"
"$PLEXADM" collection add-search "01: Activity: Double Penetration" " DP "
"$PLEXADM" collection add-search "01: Activity: Double Penetration" " Double Penetration "
"$PLEXADM" collection add-search "01: Cumshot: Facial" "facial"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "daddy"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step brother"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step dad"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step daughter"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step mom"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step sis"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step-brother"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step-dad"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step-daughter"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step-mom"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "step-sis"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "stepbrother"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "stepdad"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "stepdaughter"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "stepmom"
"$PLEXADM" collection add-search "01: Theme: Fauxcest" "stepsis"
"$PLEXADM" collection add-search "01: Activity: Fingering" "finger"
"$PLEXADM" collection add-search "01: Prop: Fuck Machine" "fuck machine"
"$PLEXADM" collection add-search "01: Prop: Fuck Machine" "fuckmachine"
"$PLEXADM" collection add-search "01: Prop: Fuck Machine" "jessky"
"$PLEXADM" collection add-search "01: Theme: GFE" "gfe"
"$PLEXADM" collection add-search "01: Theme: GFE" "girlfriend experience"
"$PLEXADM" collection add-search "01: Theme: Goth" "goth"
"$PLEXADM" collection add-search "01: Prop: Hot Wax" " wax "
"$PLEXADM" collection add-search "01: Theme: Interview" " Interview"
"$PLEXADM" collection add-search "01: Prop: Latex" "latex"
"$PLEXADM" collection add-search "01: Composition: Lesbian" " gg "
"$PLEXADM" collection add-search "01: Composition: Lesbian" "Lesbian"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "club show"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "cum show"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "cumshow"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "live stream"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "livestream"
"$PLEXADM" collection add-search "01: Theme: Live Stream" "public show"
"$PLEXADM" collection add-search "01: Composition: Orgy" " Orgies "
"$PLEXADM" collection add-search "01: Composition: Orgy" "Orgy"
"$PLEXADM" collection add-search "01: Prop: Oil" " Oil "
"$PLEXADM" collection add-search "01: Prop: Oil" " Oiled "
"$PLEXADM" collection add-search "01: Prop: Oil" " Oily "
"$PLEXADM" collection add-search "01: Prop: Oil" " Oiling "
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "Vibrator"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "bj tease"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "dildo"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "fuck machine"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "fuckmachine"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "hitachi"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "jessky"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "strap"
"$PLEXADM" collection add-search "01: Prop: Sex Toys" "toy"
"$PLEXADM" collection add-search "01: Composition: Solo" "herself"
"$PLEXADM" collection add-search "01: Composition: Solo" "myself"
"$PLEXADM" collection add-search "01: Prop: Strap On" "strap"
"$PLEXADM" collection add-search "01: Theme: Teacher/Student" "Teacher"
"$PLEXADM" collection add-search "01: Prop: Water" "shower"
"$PLEXADM" collection add-search "01: Cumshot: Throatpie" "throatpie"
"$PLEXADM" collection add-search "01: Hair: Blonde" "blond"
"$PLEXADM" collection add-search "01: Hair: Brunette" "brunette"
"$PLEXADM" collection add-search "01: Hair: Red" "Red head"
"$PLEXADM" collection add-search "01: Hair: Red" "Redhead"
